// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBey_G710VUubuNisRHbKU2De8mEEARgfw',
    appId: '1:899681713435:web:8fe0ea1a16bab2f49827be',
    messagingSenderId: '899681713435',
    projectId: 'mobilecomp-4b17b',
    authDomain: 'mobilecomp-4b17b.firebaseapp.com',
    databaseURL: 'https://mobilecomp-4b17b-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomp-4b17b.firebasestorage.app',
    measurementId: 'G-FME7TYVWTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDedKq-NRuqRb6uybvfQXSF0hDTuUl4M1s',
    appId: '1:899681713435:android:4964e8970dfa3d879827be',
    messagingSenderId: '899681713435',
    projectId: 'mobilecomp-4b17b',
    databaseURL: 'https://mobilecomp-4b17b-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomp-4b17b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR0mzGbtkKJF6WhbwcHiEbvEIWGw8jFtg',
    appId: '1:899681713435:ios:300c792df2c4270d9827be',
    messagingSenderId: '899681713435',
    projectId: 'mobilecomp-4b17b',
    databaseURL: 'https://mobilecomp-4b17b-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomp-4b17b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR0mzGbtkKJF6WhbwcHiEbvEIWGw8jFtg',
    appId: '1:899681713435:ios:300c792df2c4270d9827be',
    messagingSenderId: '899681713435',
    projectId: 'mobilecomp-4b17b',
    databaseURL: 'https://mobilecomp-4b17b-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomp-4b17b.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBey_G710VUubuNisRHbKU2De8mEEARgfw',
    appId: '1:899681713435:web:7cf10444dd4b78a49827be',
    messagingSenderId: '899681713435',
    projectId: 'mobilecomp-4b17b',
    authDomain: 'mobilecomp-4b17b.firebaseapp.com',
    databaseURL: 'https://mobilecomp-4b17b-default-rtdb.firebaseio.com',
    storageBucket: 'mobilecomp-4b17b.firebasestorage.app',
    measurementId: 'G-XMY28VKT3H',
  );
}
